server {
    listen 80;
    server_name localhost;
    root /app/web;
    index index.php;

    # Отключаем вывод версии nginx в заголовках
    server_tokens off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000; # 'php' - это имя сервиса из docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Запрещаем доступ к файлам .ht
    location ~ /\.ht {
        deny all;
    }

    # Кэширование статичных файлов
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1M;
        add_header Cache-Control "public";
    }
}